openapi: 3.0.0
info:
  title: PIX API
  version: "1.0.0"
  description: Documentação da API PIX
paths:
  /payments:
    get:
      summary: Listar pagamentos
      responses:
        "200":
          description: OK
